# This file was generated by GoReleaser. DO NOT EDIT.
cask "tera" do
  version "0.4.2"

  on_macos do
    sha256 "ad89845188da70d9ffd0777f4b133b00d793f7945363f70fcb4505bd795fb7fa"
    url "https://github.com/teraflock/flockd/releases/download/v#{version}/flockd_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "d6e95ca498896302be784c373735d5d75a0759d71deeed5b3eaa6bd7e3abc7f9"
      url "https://github.com/teraflock/flockd/releases/download/v#{version}/flockd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1befefee0a2873d25f9a6d055cc092e43cd46589403b2c575774fb1b17e7863d"
      url "https://github.com/teraflock/flockd/releases/download/v#{version}/flockd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tera"
  desc "Teraflock node daemon + CLI — earn credits serving LLM inference on idle hardware"
  homepage "https://teraflock.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flockd"
  binary "tera"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tera"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flockd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Binaries are not yet notarized (beta); the cask strips the macOS
    quarantine flag on install. To join the mesh you need an invite from
    teraflock.ai — then:
      tera login      # opens the claim page in your browser
      tera up         # installs and starts the background service
      tera dashboard  # watch it earn
  EOS
end
