# This file was generated by GoReleaser. DO NOT EDIT.
cask "tera" do
  version "0.6.1"

  on_macos do
    sha256 "d89ada5acd6abddbcce50f7d331c130a3d97933b10c00aa4508753796a06858b"
    url "https://github.com/teraflock/flockd/releases/download/v#{version}/flockd_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "eb9958614f4fd13d4556f282e21e5832bdc3544f40c09716ce0002c70ceed5b3"
      url "https://github.com/teraflock/flockd/releases/download/v#{version}/flockd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c2fb3e5fa83963b723cd663e378d4c59eb29d31326e316c3a8f280983150c7f"
      url "https://github.com/teraflock/flockd/releases/download/v#{version}/flockd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tera"
  desc "Teraflock node daemon + CLI — earn credits serving LLM inference on idle hardware"
  homepage "https://teraflock.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flockd"
  binary "tera"

  postflight do
    if OS.mac?
      opoo "tera #{version} is a beta build that is not yet notarized; stripping the quarantine flag so it runs."
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tera"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flockd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To join the mesh you need an invite from teraflock.ai — then:
      tera login      # opens the claim page in your browser
      tera up         # installs and starts the background service
      tera dashboard  # watch it earn
  EOS
end
