# Generated by scripts/release/publish-cask.sh in teraflock/flockd. DO NOT EDIT.
#
# Installs the notarized, stapled installer package rather than the bare
# binaries: files placed by an installer carry no quarantine attribute, so
# neither the install nor the daemon's first launch under launchd waits on
# a Gatekeeper dialog (teraflock/flockd#47). The package installs to
# /usr/local/bin, which is why this cask asks for your password once.
cask "tera" do
  version "0.6.7"
  sha256 "0cc8d02024ffa5d9f7710642133d198c01c76f9dabbb2f46e7c9ea3888cc9b37"

  url "https://github.com/teraflock/flockd/releases/download/v#{version}/teraflock_#{version}_darwin_all.pkg"
  name "tera"
  desc "Teraflock node daemon + CLI — earn credits serving LLM inference on idle hardware"
  homepage "https://teraflock.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on macos: :monterey

  pkg "teraflock_#{version}_darwin_all.pkg"

  uninstall pkgutil: "ai.teraflock.tera",
            launchctl: "dev.teraflock.flockd"

  caveats <<~EOS
    To join the mesh you need an invite from teraflock.ai — then:
      tera login      # opens the claim page in your browser
      tera up         # installs and starts the background service
      tera dashboard  # watch it earn
  EOS
end
