# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flock < Formula
  desc "Teraflock node daemon + CLI — earn credits serving LLM inference on idle hardware"
  homepage "https://teraflock.ai"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/teraflock/flockd/releases/download/v0.1.0/flockd_0.1.0_darwin_all.tar.gz"
    sha256 "2ddfd3ed72335f2c7c746801583edb1a8c5358b5c8089595153c6eb19547a05f"

    define_method(:install) do
      bin.install "flockd"
      bin.install "flock"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/teraflock/flockd/releases/download/v0.1.0/flockd_0.1.0_linux_amd64.tar.gz"
      sha256 "d6178276459839711adec5985b10c0c52fadc4dcddf040e90303227c332e5dc1"
      define_method(:install) do
        bin.install "flockd"
        bin.install "flock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/teraflock/flockd/releases/download/v0.1.0/flockd_0.1.0_linux_arm64.tar.gz"
      sha256 "64203f9f1c3ae77227af4f93ea25dcd5c440dab0b5ec6caaafa9fa8521fd34bc"
      define_method(:install) do
        bin.install "flockd"
        bin.install "flock"
      end
    end
  end

  def caveats
    <<~EOS
      Binaries are not yet notarized (beta). To join the mesh you need an
      invite from teraflock.ai — then:
        flock login      # opens the claim page in your browser
        flock up         # installs and starts the background service
        flock dashboard  # watch it earn
    EOS
  end
end
