# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flock < Formula
  desc "Teraflock node daemon + CLI — earn credits serving LLM inference on idle hardware"
  homepage "https://teraflock.ai"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/teraflock/flockd/releases/download/v0.1.3/flockd_0.1.3_darwin_all.tar.gz"
    sha256 "8e5fba6c6ffeff90320097c8270e459379150ea309a90ee6b6776f3f3979fca0"

    define_method(:install) do
      bin.install "flockd"
      bin.install "flock"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/teraflock/flockd/releases/download/v0.1.3/flockd_0.1.3_linux_amd64.tar.gz"
      sha256 "0744ac9504ba2298ff71bbb8705bb48dc17feeb5ce27104260861ef65c2ff994"
      define_method(:install) do
        bin.install "flockd"
        bin.install "flock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/teraflock/flockd/releases/download/v0.1.3/flockd_0.1.3_linux_arm64.tar.gz"
      sha256 "51bc897489c6d6d6012bfdebc90ace72002c59e18c4564179880281ac7115f4d"
      define_method(:install) do
        bin.install "flockd"
        bin.install "flock"
      end
    end
  end

  def caveats
    <<~EOS
      Binaries are not yet notarized (beta). To join the mesh you need an
      invite from teraflock.ai — then:
        flock login      # opens the claim page in your browser
        flock up         # installs and starts the background service
        flock dashboard  # watch it earn
    EOS
  end
end
